import re

text = """ARTICLE TITLE: 4 Audio Innovations Transforming Freight Operations
META TITLE: Audio Innovations in Digital Freight Management
META DESCRIPTION: Explore how audio branding, acoustic AI, spatial audio, and telematics integration are reshaping digital freight operations and predictive maintenance.

FULL TEXT:
Freight management is a high-stakes, fast-moving business where minor technological shifts lower operational expenses across the board. Audio tools have transformed how digital freight systems operate affordably, improving processes across four main areas.

Audio Branding and Marketing SFX

Brand identity matters in shipping. Freight companies are adding specialized AI SFX into marketing strategies to stand out from competitors while building stronger connections with clients and workers. Marketers place a distinct, repeatable audio cue at the end of commercial spots. Over time, that theme song or jingle lodges in listener memory. It builds recall and gives a corporate identity distinct personality.

Real-Time Updates via Telematics Integration

Live broadcasting during transit events delivers immediate operational updates. Dispatchers and logistics coordinators send live audio directly to stakeholders and field teams. On-site workers and vehicle operators hear updates through smart audio hardware paired with dispatch and telematics integration.

Earlier workflows relied on checking web portals or phone text alerts. Users read static timeline updates after events occurred. Direct audio feeds keep participants involved in real time, making stakeholders feel like they are sitting in the driver's seat.

Immediate status checks matter during tight schedules or when moving hazardous, time-sensitive cargo. Monitoring each leg of the journey allows managers to adjust operational plans without delay.

Acoustic AI and Predictive Maintenance

Acoustic AI in routine maintenance helps prevent sudden equipment breakdowns. Monitoring systems evaluate sounds generated by trucks, cars, and industrial machinery to identify mechanical problems before failure occurs. Catching component wear early reduces downtime and cuts financial losses. Long-haul shipments, such as cargo moving across the globe to Australia, require total equipment reliability. Acoustic monitoring identifies issues early, keeping freight moving smoothly.

Spatial Audio for Staff Training

Complex freight operations demand thorough employee training. Weak preparation breaks entire supply chains. Immersive audio experiences created with 3D soundscapes and spatial audio make instruction clearer and easier to retain. New hires and veteran staff practice handling emergency situations and operating heavy machinery in realistic sound environments. Practical audio instruction helps workers build confidence quickly.

Final Thoughts

Audio tech touches every corner of digital freight management, from marketing sound design to maintenance diagnostics and safety instruction. As sound tools continue to evolve, shipping operations will gain even higher levels of efficiency.
"""

def audit(t):
    print("--- START AUDIT ---")
    
    # 1. EM DASH
    if "—" in t or "--" in t:
        print("[FAIL] Rule 1: Em-dash found!")
    else:
        print("[PASS] Rule 1: No em-dashes.")
        
    # 2. AI CLICHES
    cliches = [
        "fast-paced world", "delve", "not just", "crucial role", "paramount", "game-changer",
        "game changer", "testament", "in conclusion", "landscape", "tapestry", "realm",
        "ever-evolving", "harnessing", "unlocking", "revolutionize", "beacon", "fostering",
        "paving the way", "vital role", "key role", "boasts", "cutting-edge"
    ]
    found_cliches = [c for c in cliches if re.search(r'\b' + re.escape(c) + r'\b', t, re.IGNORECASE)]
    if found_cliches:
        print(f"[FAIL] Rule 2: Cliches found: {found_cliches}")
    else:
        print("[PASS] Rule 2: No AI clichés.")
        
    # 3. METAPHORS
    # Check metaphors: "sitting in the driver's seat" is 1. Any others?
    print("Metaphor check: 'driver's seat' used once.")

    # 4. BURSTINESS / SENTENCE LENGTHS
    sentences = re.split(r'(?<=[.!?])\s+', t)
    lengths = [len(s.split()) for s in sentences if s.strip() and not s.startswith("ARTICLE TITLE:") and not s.startswith("META TITLE:") and not s.startswith("META DESCRIPTION:") and not s.startswith("FULL TEXT:")]
    print(f"Sentence length count: {len(lengths)}, Min words: {min(lengths)}, Max words: {max(lengths)}")
    print("Sentence lengths sample:", lengths[:10])

    # 5. CONNECTORS (Rule 6)
    connectors = ["that's why", "which is why", "this is because", "because of this", "therefore", "as a result"]
    found_conn = [c for c in connectors if re.search(r'\b' + re.escape(c) + r'\b', t, re.IGNORECASE)]
    if found_conn:
        print(f"[FAIL] Rule 6: Connectors found: {found_conn}")
    else:
        print("[PASS] Rule 6: No banned connectors.")

    # 6. CONTRASTIVE NEGATIONS (Rule 7)
    # Check instances of "not X, but Y", "X, not Y", "instead of", "rather than"
    cn_patterns = [
        r'\bnot\b.*?\bbut\b',
        r'\binstead of\b',
        r'\brather than\b'
    ]
    cn_matches = []
    for p in cn_patterns:
        matches = re.findall(p, t, re.IGNORECASE)
        cn_matches.extend(matches)
    print(f"Contrastive negations detected: {len(cn_matches)} -> {cn_matches}")

    # 7. REQUIRED TREND KEYWORDS
    keywords = ["acoustic AI", "predictive maintenance", "spatial audio", "audio branding", "telematics integration"]
    for kw in keywords:
        if kw.lower() in t.lower():
            print(f"[PASS] Keyword found: '{kw}'")
        else:
            print(f"[FAIL] Missing keyword: '{kw}'")

audit(text)
