import json
import re
import docx
import subprocess

# Final refined text addressing all audit feedback and Rule 11 constraints

title = "Converting Maritime Logistics PDF Reports into Interactive PowerPoint Slides"
meta_title = "Maritime Logistics: Converting PDF Reports into PPTX"
meta_description = "Learn how to convert PDF reports to PPTX using Adobe Acrobat on web, Android, iOS, and desktop for maritime analytics and freight reporting."

body_markdown = """International shipping operations increasingly rely on PowerPoint slides rather than static PDF documents when presenting maritime analytics to partners, clients, and regulatory bodies. Turning static reports into visual slide decks enables logistics vendors to share intricate operational metrics clearly during team meetings.

### Converting Web-Based PDF Reports in Adobe Acrobat Online

Adobe Acrobat online services provides a browser-based workflow for converting individual PDF documents.

1. Open Adobe Acrobat online services in your web browser.
2. Scroll down to locate the 'Convert PDF to PPT' tool and click 'Try for free'.
3. Select 'Select a file' and pick your target PDF report from the pop-up window.
4. Allow the file to upload while Acrobat completes the processing phase.
5. Log in to retrieve and download the completed .pptx file at no cost.

While Adobe's tools are highly reliable, double-check your exported slides for formatting mistakes before presenting at your logistics meetings.

### Mobile PDF Conversions on Android Devices

Personnel handling cargo tracking reporting on Android mobile devices can execute conversions directly through a web browser.

1. Launch Adobe Acrobat online services in your Android browser.
2. Tap the three-line menu icon in the upper-left corner of your screen.
3. Select 'Convert' from the menu choices, then tap 'Convert PDF to PPT'.
4. Tap 'Select a file', open your file browser, and choose the PDF document.
5. Wait for the automatic file conversion to complete.
6. Log in to download the new PowerPoint deck.

### Mobile PDF Conversions on iOS Devices

Apple users can convert analytics documents using Safari on iPhones or iPads.

1. Open Safari and navigate to the Adobe Acrobat PDF to PPT converter page.
2. Tap 'Select a file' to locate and choose your target PDF document.
3. Allow the system to perform the file conversion immediately.
4. Log in to download the finished PPT presentation for free.

### Desktop Bulk PDF to PPTX Conversion

Handling large volumes of maritime logistics data often involves multiple PDF reports. Adobe Acrobat allows desktop users to convert these files in bulk.

1. Launch Adobe Acrobat on your computer.
2. Click 'File' in the menu, choose 'Open', and select all relevant PDF reports.
3. Locate the 'Export' option on the primary toolbar.
4. Select 'Microsoft PowerPoint' under the PowerPoint Format (.PPTX) export options.
5. Click 'Export' or 'Save' to convert all selected files simultaneously.
6. Choose a destination folder to save your converted slide files.

### Structuring Tariff Calculations and Freight Metrics

Raw PDF reports generated by an online freight calculator often hide crucial cost factors inside dense data tables. Visualizing a clear freight rate breakdown on PowerPoint slides using charts and graphs helps decision-makers grasp how cost variables affect total transportation expenses:

- Base shipping rate
- Fuel surcharges
- Terminal handling charges
- Additional fees and surcharges

Displaying rate index analysis and tracking metrics through logistics presentation tools gives logistics vendors clear visibility on how fuel price changes and peak season surcharges impact overall shipping costs."""

# Programmatic verification
em_dash_chars = ['—', '--', '–']

def count_em_dashes(text):
    c = 0
    for e in em_dash_chars:
        c += text.count(e)
    return c

all_text = f"{title}\n{meta_title}\n{meta_description}\n{body_markdown}"
em_dash_total = count_em_dashes(all_text)

meta_title_len = len(meta_title)
meta_desc_len = len(meta_description)

print(f"Em-dash count across all text: {em_dash_total}")
print(f"Meta title length: {meta_title_len} chars (Max 60)")
print(f"Meta description length: {meta_desc_len} chars (Max 155)")

# Save docx
doc = docx.Document()
h1 = doc.add_heading(title, level=1)
p_meta = doc.add_paragraph()
r_meta = p_meta.add_run(f"Meta Title: {meta_title}\nMeta Description: {meta_description}")
r_meta.italic = True
r_meta.font.size = docx.shared.Pt(9)

doc.add_paragraph() # spacing

for paragraph in body_markdown.split('\n\n'):
    p_str = paragraph.strip()
    if not p_str:
        continue
    if p_str.startswith('### '):
        doc.add_heading(p_str.replace('### ', ''), level=2)
    elif p_str.startswith('- '):
        lines = p_str.split('\n')
        for line in lines:
            if line.startswith('- '):
                doc.add_paragraph(line.replace('- ', ''), style='List Bullet')
    elif re.match(r'^\d+\.\s', p_str):
        lines = p_str.split('\n')
        for line in lines:
            m = re.match(r'^\d+\.\s*(.*)', line)
            if m:
                doc.add_paragraph(m.group(1), style='List Number')
            else:
                doc.add_paragraph(line)
    else:
        doc.add_paragraph(p_str)

docx_filename = "/opt/hermes/profiles/archie/Maritime_Logistics_PDF_to_PPT_Rewrite.docx"
doc.save(docx_filename)
print(f"DOCX created: {docx_filename}")
