import re

final_article = """ARTICLE TITLE: 4 Audio Innovations Transforming Freight Operations
META TITLE: Audio Innovations in Digital Freight Management
META DESCRIPTION: Explore how audio branding, acoustic AI, spatial audio, and telematics integration are reshaping digital freight operations and predictive maintenance.

FULL TEXT:
Freight management is a high-stakes, fast-moving business where minor technological shifts lower operational expenses across the board. Audio tools have transformed how digital freight systems operate affordably, improving processes across key operational areas.

Audio Branding and Marketing SFX

Brand identity matters in shipping. Freight companies are adding specialized AI SFX into marketing strategies to stand out from competitors while building stronger connections with clients and workers. 

Marketers place a distinct, repeatable audio cue at the end of commercial spots. Over time, that theme song or jingle lodges in listener memory. It builds recall and gives a corporate identity distinct personality.

Real-Time Updates via Telematics Integration

Dispatchers sending live audio directly to field teams keep every participant informed as shipment milestones occur. On-site workers and vehicle operators receive live updates through smart audio hardware paired with dispatch and telematics integration.

Earlier workflows relied on checking web portals or phone text alerts. Users read static timeline updates after events occurred. Direct audio feeds keep participants involved in real time, making stakeholders feel like they are sitting in the driver's seat.

Immediate status checks matter during tight schedules or when moving hazardous, time-sensitive cargo. Monitoring each leg of the journey allows managers to adjust operational plans without delay.

Acoustic AI and Predictive Maintenance

Acoustic AI in routine maintenance helps prevent sudden equipment breakdowns. Monitoring systems evaluate sounds generated by transport vehicles and industrial machinery to identify mechanical problems before failure occurs. Catching component wear early reduces downtime and cuts financial losses. Long-haul shipments, such as cargo moving across the globe to Australia, require total equipment reliability. Acoustic monitoring identifies issues early, keeping freight moving smoothly.

Spatial Audio for Staff Training

Complex freight operations demand thorough employee training. Weak preparation breaks supply chains. Immersive audio experiences created with 3D soundscapes and spatial audio make instruction clearer and easier to retain. New workers and experienced personnel practice handling emergency situations and operating heavy machinery in realistic sound environments. Practical audio instruction helps workers build confidence quickly.

Final Thoughts

Audio tech touches every corner of digital freight management, from marketing audio to predictive diagnostics and workforce training. As sound tools continue to evolve, shipping operations will gain higher levels of efficiency.
"""

def verify_full_submission(text_to_check):
    lines = text_to_check.strip().split('\n')
    
    art_title = ""
    meta_title = ""
    meta_desc = ""
    
    for l in lines:
        if l.startswith("ARTICLE TITLE:"):
            art_title = l.split("ARTICLE TITLE:")[1].strip()
        elif l.startswith("META TITLE:"):
            meta_title = l.split("META TITLE:")[1].strip()
        elif l.startswith("META DESCRIPTION:"):
            meta_desc = l.split("META DESCRIPTION:")[1].strip()
            
    print(f"ARTICLE TITLE ({len(art_title)} chars): {art_title}")
    print(f"META TITLE ({len(meta_title)} chars): {meta_title}")
    print(f"META DESCRIPTION ({len(meta_desc)} chars): {meta_desc}")
    
    assert len(art_title) <= 60, "Article title too long!"
    assert len(meta_title) <= 60, "Meta title too long!"
    assert len(meta_desc) <= 155, "Meta desc too long!"
    
    # Check em dashes
    assert "—" not in text_to_check and "--" not in text_to_check, "Em dash found!"
    
    # Check keywords
    keywords = ["acoustic AI", "predictive maintenance", "spatial audio", "audio branding", "telematics integration"]
    for kw in keywords:
        assert kw.lower() in text_to_check.lower(), f"Keyword {kw} missing!"
        
    print("Verification complete: ALL CONSTRAINTS STRICTLY PASSED!")

verify_full_submission(final_article)
